/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WrestlersIndexRouteImport } from './routes/wrestlers/index'
import { Route as TitlesIndexRouteImport } from './routes/titles/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as WrestlersWrestlerIdRouteImport } from './routes/wrestlers/$wrestlerId'
import { Route as TitlesTitleIdRouteImport } from './routes/titles/$titleId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrestlersIndexRoute = WrestlersIndexRouteImport.update({
  id: '/wrestlers/',
  path: '/wrestlers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesIndexRoute = TitlesIndexRouteImport.update({
  id: '/titles/',
  path: '/titles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrestlersWrestlerIdRoute = WrestlersWrestlerIdRouteImport.update({
  id: '/wrestlers/$wrestlerId',
  path: '/wrestlers/$wrestlerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesTitleIdRoute = TitlesTitleIdRouteImport.update({
  id: '/titles/$titleId',
  path: '/titles/$titleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/wrestlers/$wrestlerId': typeof WrestlersWrestlerIdRoute
  '/events/': typeof EventsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/titles/': typeof TitlesIndexRoute
  '/wrestlers/': typeof WrestlersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/wrestlers/$wrestlerId': typeof WrestlersWrestlerIdRoute
  '/events': typeof EventsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/titles': typeof TitlesIndexRoute
  '/wrestlers': typeof WrestlersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/wrestlers/$wrestlerId': typeof WrestlersWrestlerIdRoute
  '/events/': typeof EventsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/titles/': typeof TitlesIndexRoute
  '/wrestlers/': typeof WrestlersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/confirm'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/titles/$titleId'
    | '/wrestlers/$wrestlerId'
    | '/events/'
    | '/reviews/'
    | '/titles/'
    | '/wrestlers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/confirm'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/titles/$titleId'
    | '/wrestlers/$wrestlerId'
    | '/events'
    | '/reviews'
    | '/titles'
    | '/wrestlers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/auth/confirm'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/titles/$titleId'
    | '/wrestlers/$wrestlerId'
    | '/events/'
    | '/reviews/'
    | '/titles/'
    | '/wrestlers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  TitlesTitleIdRoute: typeof TitlesTitleIdRoute
  WrestlersWrestlerIdRoute: typeof WrestlersWrestlerIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  TitlesIndexRoute: typeof TitlesIndexRoute
  WrestlersIndexRoute: typeof WrestlersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrestlers/': {
      id: '/wrestlers/'
      path: '/wrestlers'
      fullPath: '/wrestlers/'
      preLoaderRoute: typeof WrestlersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles/': {
      id: '/titles/'
      path: '/titles'
      fullPath: '/titles/'
      preLoaderRoute: typeof TitlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrestlers/$wrestlerId': {
      id: '/wrestlers/$wrestlerId'
      path: '/wrestlers/$wrestlerId'
      fullPath: '/wrestlers/$wrestlerId'
      preLoaderRoute: typeof WrestlersWrestlerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles/$titleId': {
      id: '/titles/$titleId'
      path: '/titles/$titleId'
      fullPath: '/titles/$titleId'
      preLoaderRoute: typeof TitlesTitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  TitlesTitleIdRoute: TitlesTitleIdRoute,
  WrestlersWrestlerIdRoute: WrestlersWrestlerIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  TitlesIndexRoute: TitlesIndexRoute,
  WrestlersIndexRoute: WrestlersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
